GET_MONTHLY_REVENUE = """SELECT sum(total_invoice_amount_after_tax)
    FROM INVOICE_T
    WHERE EXTRACT(MONTH FROM INVOICE_DATE) = %s
        AND EXTRACT(YEAR FROM INVOICE_DATE) = %s;"""

GET_FINANCIAL_YEAR_REVENUE = """SELECT SUM(TOTAL_INVOICE_AMOUNT_AFTER_TAX) 
    FROM INVOICE_T
    WHERE CASE
        WHEN EXTRACT(MONTH FROM INVOICE_DATE) <= 3 
            THEN (EXTRACT(MONTH FROM INVOICE_DATE) > 3 AND EXTRACT(YEAR FROM INVOICE_DATE) = %s-1) OR (EXTRACT(MONTH FROM INVOICE_DATE) <= 3 AND EXTRACT(YEAR FROM INVOICE_DATE) = %s)
            ELSE (EXTRACT(MONTH FROM INVOICE_DATE) > 3 AND EXTRACT(YEAR FROM INVOICE_DATE) = %s)
        END;"""

GET_PENDING_INVOICES = """SELECT COUNT(INVOICE_ID)
    FROM INVOICE_T
    WHERE TOTAL_INVOICE_AMOUNT_AFTER_TAX > AMOUNT_PAID"""

GET_RECENT_INVOICE_INFO = """SELECT T1.INVOICE_ID,
	T1.INVOICE_NUMBER,
	T2.CUSTOMER_COMPANY_GST,
    T1.TOTAL_INVOICE_AMOUNT_AFTER_TAX,
	T2.CUSTOMER_COMPANY_NAME,
	T1.INVOICE_DATE,
	CASE
					WHEN TOTAL_INVOICE_AMOUNT_AFTER_TAX > AMOUNT_PAID THEN 'Pending'
					ELSE 'Complete'
	END AS STATUS
FROM INVOICE_T AS T1
JOIN PUBLIC.CUSTOMER_INFO_T AS T2 ON T1.CUSTOMER_ID = T2.CUSTOMER_ID
WHERE T1.COMPANY_ID = %s;"""